doctrine:
  dbal:
    driver: "%env(resolve:DATABASE_DRIVER)%"
    host: "%env(resolve:DATABASE_HOST)%"
    user: "%env(DATABASE_USERNAME)%"
    password: "%env(DATABASE_PASSWORD)%"
    dbname: "%env(resolve:DATABASE_NAME)%"
    server_version: "%env(resolve:DATABASE_SERVER_VERSION)%"
    charset: "utf8mb4"

    types:
      date: mealplan\orm\DateType
      datetime: mealplan\orm\DateTimeType
      time: mealplan\orm\TimeType
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      mealplan:
        is_bundle: false
        dir: '%kernel.project_dir%/src/main/php/mealplan/model'
        prefix: 'mealplan\model'
        alias: mealplan

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
