version: "3.8"

services:
  app:
    volumes:
      - .:/app:ro
    environment:
      USE_CACHE: "false"

  mysql:
    volumes:
      - ./database-sample.sql:/docker-entrypoint-initdb.d/20-sample.sql:ro