version: "3.8"

services:
  app:
    build: .
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      TZ: Europe/Berlin
      APP_URL: "http://localhost:8080"
      APP_ENV: dev
      DATABASE_DRIVER: pdo_mysql
      DATABASE_HOST: mysql
      DATABASE_NAME: mealplan
      DATABASE_USERNAME: mealplan
      DATABASE_PASSWORD: mealplan
      DATABASE_SERVER_VERSION: "mariadb-10.10.2"

  mysql:
    image: mariadb
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/10-db.sql:ro
    environment:
      TZ: Europe/Berlin
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: mealplan
      MYSQL_USER: mealplan
      MYSQL_PASSWORD: mealplan